service:
  name: alexathon-api-resources

custom:
  table_provas: 'provas'
  table_questoes: 'questoes'
  table_respostas: 'respostas'

provider:
  name: aws
  runtime: nodejs12.x
  stage: v1

resources:
  Resources:
    ProvaDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table_provas}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    QuestoesDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table_questoes}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    RespostasDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table_respostas}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  Outputs:
    ProvaTableArn:
      Value:
        Fn::GetAtt:
          - ProvaDynamoDBTable
          - Arn
      Export:
        Name: ${self:custom.table_provas}-ProvaTableArn
    QuestaoTableArn:
      Value:
        Fn::GetAtt:
          - QuestoesDynamoDBTable
          - Arn
      Export:
        Name: ${self:custom.table_questoes}-QuestaoTableArn
    RespostaTableArn:
      Value:
        Fn::GetAtt:
          - RespostasDynamoDBTable
          - Arn
      Export:
        Name: ${self:custom.table_respostas}-RespostaTableArn
