service:
  name: alexathon-api

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: v1
  memorySize: 256
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: '*'
  environment:
    DEBUG: true

functions:
  samples:
    handler: src/api/bin/index.handler
    events:
      - http:
          path: samples/{proxy+}
          method: ANY
          cors: true
