service:
  name: alexathon-api

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  stage_app: ${opt:cfg}
  local:
    debug: true
    docs: true
  dev:
    debug: true
    docs: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: v1
  memorySize: 256
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: '*'
  environment:
    STAGE: ${opt:cfg}
    ENABLE_DOCS: ${self:custom.${opt:cfg}.docs, 'false'}
    DEBUG: ${self:custom.${opt:cfg}.debug, 'false'}

functions:
  samples:
    handler: src/api/bin/index.handler
    events:
      - http:
          path: samples/{proxy+}
          method: ANY
          cors: true
