service:
  name: alexathon-api

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  table: ${file(./resources.yml):custom.table}

provider:
  name: aws
  runtime: nodejs12.x
  stage: v1
  memorySize: 256
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: '*'
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - 'Fn::ImportValue': ${self:custom.table}-ProvaTableArn
  environment:
    DEBUG: true
    TABLE: ${self:custom.table}

functions:
  samples:
    handler: src/api/bin/index.handler
    events:
      - http:
          path: api/{proxy+}
          method: ANY
          cors: true
